name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: cd cicdtf && terraform init -reconfigure

      - name: Terraform Validate
        run: cd cicdtf && terraform validate

      - name: Terraform Plan
        run: cd cicdtf && terraform plan -out=tfplan
        env:
          TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: cd cicdtf && terraform apply -auto-approve tfplan
        env:
          TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}
