name: Terraform CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

env:
  AWS_REGION: ap-south-1 # Set your AWS region here

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    # Use the Bash shell for all steps
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0 # Specify a compatible Terraform version, adjust if needed

      - name: Terraform Init
        id: init
        run: terraform init -upgrade # Use -upgrade to ensure providers are up-to-date
        working-directory: ./cicdtf # Your Terraform root directory

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        working-directory: ./cicdtf # Your Terraform root directory
        env:
          # Pass the public key as an environment variable to Terraform
          # Ensure this secret contains the exact, single-line ED25519 public key.
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only apply on push to main
        run: terraform apply -auto-approve -input=false
        working-directory: ./cicdtf # Your Terraform root directory
        env:
          # Pass the public key as an environment variable to Terraform for apply
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}