name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      # You can create different environments (e.g., 'dev', 'prod') in GitHub for different AWS accounts/configurations
      name: production

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1 # Your specified region

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Use a compatible Terraform version (e.g., 1.9.1 or latest stable)

      - name: Terraform Init
        id: init
        # IMPORTANT: Set working-directory for each Terraform command
        working-directory: cicdtf/
        run: terraform init -backend-config="bucket=terraform-state-ssr123-ap-south-1" -backend-config="key=terraform.tfstate" -backend-config="region=ap-south-1" -backend-config="dynamodb_table=DB_Terraform_State_Bucket"

      - name: Terraform Validate
        id: validate
        # IMPORTANT: Set working-directory for each Terraform command
        working-directory: cicdtf/
        run: terraform validate

      - name: Terraform Plan
        id: plan
        # IMPORTANT: Set working-directory for each Terraform command
        working-directory: cicdtf/
        run: terraform plan -no-color -out=tfplan
        # Store the plan as an artifact for later review/manual approval if needed
        # This is a common practice for security and control
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          # Path is relative to the runner's workspace, but the tfplan file is created inside cicdtf/
          path: cicdtf/tfplan 

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only apply on push to main branch
        # IMPORTANT: Set working-directory for each Terraform command
        working-directory: cicdtf/
        run: terraform apply -auto-approve tfplan

      # The 'Terraform Destroy (Manual Trigger)' step has been removed.
